print()
print("=-"*60)
print()
print("--------------quociente da divisão de A por B------------------")
print()
print("=-"*60)
print() 
a= int(input("Digite o valor de A: "))
b = int(input("Digite o valor de B: "))
resul= a / b 
print("O resultado da divisão dos numeros {} e {} é {}".format(a, b, resul))
