print()
print("=-"*60)
print()
print("---------------Numero invertido------------------")
print()
print("=-"*60)
print()

n1=int(input("Digite o numero que voce deseja ver o contrario: "))
numeroInvertido = int(str(n1)[::-1])
print()
print("=-"*60)
print()
print("o numero espelhado é: {}".format(numeroInvertido))
print()
print("=-"*60)
print()
