from fractions import Fraction

print()
print("=-"*60)
print()
print("----------------Calculo de resistencia eletrica-----------------")
print()
print("=-"*60)
print()

r1=int(input("Digite o valor da sua primeira resitencia: "))
print()
print("=-"*60)
print()
r2=int(input("Digite o valor da sua segunda resitencia: "))
print()
print("=-"*60)
print()
r3=int(input("Digite o valor da sua terceira resitencia: "))
print()
print("=-"*60)
print()
a= Fraction (1,r1)
b= Fraction (1,r2)
c = Fraction(1, r3)
resistencia= ((a) + (b) + (c))
print(resistencia)
print("A resistencia equivalente desses circuito é: {}".format(resistencia))
print()
print("=-"*60)
print()