print()
print("=-"*60)
print("-------------------O quoeciente e a divisão---------------")
print()
print("=-"*60)
print()
n1 = int(input("Digite o seu primeiro numero: "))
print()
print("=-"*60)
n2 = int(input("Digite o seu segundo numero: "))
print()
print("=-"*60)
print()

print("Quoeciente: ", n1 / n2)
print()
print("=-"*60)
print()
print("Restos: ", n1 % n2)
