print()
print("=-"*60)
print()
print("--------------Vocal ou não------------------")
print()
print("=-"*60)
print() 
n1=str(input("Digite a letra que deseja saber se é uma vocal: "))
print()
print("=-"*60)
print()
if n1 =='a':
     print("A letra {} é uma vocal".format(n1))
     print()
     print("=-"*60)
     print()
elif n1 == 'e':
    print("A letra {} é uma vocal".format(n1))
    print()
    print("=-"*60)
    print()
elif n1 == 'i':
     print("A letra {} é uma vocal".format(n1))
     print()
     print("=-"*60)
     print()
elif n1 == 'o':
     print("A letra {} é uma vocal".format(n1))
     print()
     print("=-"*60)
     print()
elif n1 == 'u':
     print("A letra {} é uma vocal".format(n1))
     print()
     print("=-"*60)
     print()
else:
    print("A letra {} é uma consoante".format(n1))
    print()
    print("=-"*60)
    print()
