print()
print("=-"*60)
print("-------------------O Sucessor do seu numero---------------")
print()
print("=-"*60)
print()
n = int(input("Digite o seu numero inteiro: "))
print()
print("=-"*60)
print()
n1 = n + 1
print("O sucessor do seu numero é: {}".format(n1))
print()
print("=-"*60)
print()
