print()
print("=-"*60)
print()
print("----------------Calculo do tamanho do predio-----------------")
print()
print("=-"*60)
print()
n1=float (input("Digite sua Altura: "))
n2= n1 * 2 
print()
print("=-"*60)
print()
n3=float(input("Qual é o tamanho da sombra do prédio: "))
print()
print("=-"*60)
print()
n4= (n3 / n2) * 2 
print("o tamanho do prédio em metros é: {} metros ".format(n4))
print()
print("=-"*60)
print()