print()
print("=-"*60)
print()
print("-------------------numero inteiro para binario---------------")
print()
print("=-"*60)
print()
n1=int(input("Digite um numero até 32: "))
print()
print("=-"*60)
print()
if n1 > 32: 
    print("Digite um valor valido")
    print()
if n1 <= 32:
    n2 = "{0:b}".format(n1)
    print("O numero digitado em binarios é: {}".format(n2))
    print()
print("=-"*60)
print()
