print("\n=====CALCULADOR DE IDADE EM DIAS, MESES E ANOS=====")
idade=int(input("\nInforme sua idade em dias: "))
print("\nSua idade em anos: ", idade / 365)
print("\nSua idade em meses aproximadamente: ", idade * 0.0328767)
print("\nSua idade em dias é: ", idade)
print("\n=====FIM DO PROGRAMA=====")