print()
print("=-"*60)
print("-------------------Calculo do volume de uma lada de oleo---------------")
print()
print("=-"*60)
print()
n1=float(input("Qual é o raio da sua lada: "))
print()
print("=-"*60)
print()
n2=float(input("Digite a altura da sua lada: "))
print()
print("=-"*60)
print()
v=float(3.14 * (n1 * n1) * n2)
print("O volume da sua lada é: {}".format(v))
print()
print("=-"*60)
print()