print()
print("=-"*60)
print()
print("-------------------Nota Semestral de um aluno---------------")
print()
print("=-"*60)
print()
print("------------------------------Notas do 1º bimestres---------------------------")
print()
print("=-"*60)
print()
n1=float(input("Digite a nota da primeira prova: "))
print()
print("=-"*60)
print()
n2= float(input("Digite a nota da segunda prova: "))
Bi= (n1 + n2) /2
print()
print("=-"*60)
print()
print("--------------------------------------Notas do 2º bimestres----------------------------")
print()
print("=-"*60)
print()
n3= float(input("Digite a primeira nota: "))
print()
print("=-"*60)
print()
n4= float(input("Digite a segunda nota: "))
Bi2= (n3 + n4) /2
print()
print("=-"*60)
print()
Semes= (Bi + Bi2)/ 2
print("A nota do semetre do aluno é: {}".format(Semes))
print()
print("=-"*60)
print()