print()
print("=-"*60)
print()
print("-----------------Metros em Km----------------")
print()
print("=-"*60)
print()
n1=float(input("Digite a velocidade em m/s que deseja tranformar em Km/h:  "))
print()
print("=-"*60)
print()
n2= n1 * 3.6
print("A velocidade digitada pelo usuario ficou: {} Km/h".format(n2))
print()
print("=-"*60)
print()