print()
print("=-"*60)
print()
print("----------------Calcure a raiz de equação do primeiro grau-----------------")
print()
print("=-"*60)
print()
n1= int(input("Digite o valor do X: "))
print()
print("=-"*60)
print()
n2= int(input("digite o resto da equação {}x : ".format(n1)))
print()
print("=-"*60)
print()
n3 =float( - n2 / n1)
print("O  valor da raiz  é: {} ".format(n3))
print()
print("=-"*60)
print()