print()
print("=-"*60)
print()
print("----------------Valor positivo ou negativo-----------------")
print()
print("=-"*60)
print()
n1=int(input("Digite o seu numero: "))
print()

if n1 >=0: 
    print(f'O numero {n1} é positivo')
    print()
    print("=-"*60)
    print()
else: 
    print(f'O numero {n1} é negativo')
    print()
print("=-"*60)
print()